name: sericea-build-pr

on:
  pull_request:
    paths:
      - '**/Dockerfile'
permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push non-nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./non-ipu6
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:non-ipu6

      - name: Build and push nvidia Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: ./ipu6
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:ipu6
