name: Docker Build and Push on PR

on:
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: contains(github.event.pull_request.changed_files, 'Dockerfile')

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: contains(github.event.pull_request.changed_files, 'Dockerfile')

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/sericea-custom-build:v1
        if: contains(github.event.pull_request.changed_files, 'Dockerfile')

      - name: Set success status if Dockerfile not modified
        run: echo "Dockerfile was not modified, setting success status."
        if: "!contains(github.event.pull_request.changed_files, 'Dockerfile')"
        continue-on-error: true

      - name: Block merge if build fails
        if: failure()
        run: exit 1

